apiVersion: v1
data:
  HTTP_PROXY: http://${PROXY_SERVICE}/
  HTTPS_PROXY: http://${PROXY_SERVICE}/
  NO_PROXY: ${SERVICE_CIDR_SUB},localhost,${LAN_CIDR_SUB}.0.0/16,*.svc.cluster.local,svc.cluter.local 
kind: ConfigMap
metadata:
  name: custom-env
  namespace: gitlab-system
