apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: dso-keycloak
  labels:
    app: sso
  namespace: keycloak-system
spec:
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    imagePullPolicy: Always
  postgresDeploymentSpec:
    imagePullPolicy: Always
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: HTTP_PROXY
          value: http://${PROXY_SERVICE}/
        - name: HTTPS_PROXY
          value: http://${PROXY_SERVICE}/
  instances: 1
---
kind: KeycloakRealm
apiVersion: keycloak.org/v1alpha1
metadata:
  name: dso-realm
  labels:
    app: sso
  namespace: keycloak-system
spec:
  realm:
    id: dso
    realm: dso
    enabled: true
    displayName: Dso Realm
  instanceSelector:
    matchLabels:
      app: sso
