apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: admin-gitlab
  labels:
    app: sso
  namespace: keycloak-system
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    credentials:
      - temporary: false
        type: password
        value: ${KEYCLOACK_ADMIN_PASSWORD}
    username: admin@example.com
    firstName: Admin
    lastName: Admin
    email: admin@example.com
    enabled: true
    emailVerified: true
