- name: Creating kubeconfig
  copy:
    dest: "~/.kube/config"
    content: "{{lookup('vars','K8S_AUTH_KUBECONFIG')}}"

- name: Create argo project
  kubernetes.core.k8s:
    state: present
    template: ./templates/argo_project.yml.j2
