apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Gatekeeper.v1alpha1.operator.gatekeeper.sh
  name: gatekeeper-operators
  namespace: openshift-operators
