apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana-monitoring
  namespace: openshift-infra
spec:
  config:
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: true
    auth.basic:
      enabled: true
    auth.proxy:
      enabled: false
    security:
      admin_password: ${GRAFANA_ADMIN_PASSWORD}
      admin_user: admin-dso
  ingress:
    enabled: true
  #previousServiceName: grafana-service

