CREATE ROLE sonar WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'xxxxxx';


    CREATE DATABASE sonarqube
    WITH 
    OWNER = sonar
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;