apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  namespace: openshift-operators
  name: ldap-data-claim # Sets name of PV
spec:
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 20Gi # Sets volume size