apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    values:
      certmanager:
        install: true
      global:
        hosts:
          domain: .apps.${SUBDOMAIN}.${DOMAIN_NAME}
          gitlab:
            name: gitlab-op.apps.${SUBDOMAIN}.${DOMAIN_NAME}
          registry:
            name: gitlab-registry.apps.${SUBDOMAIN}.${DOMAIN_NAME}
          minio:
            name: gitlab-minio.apps.${SUBDOMAIN}.${DOMAIN_NAME}
          smartcard:
            name: gitlab-smartcard.apps.${SUBDOMAIN}.${DOMAIN_NAME}
          kas:
            name: gitlab-kas.apps.${SUBDOMAIN}.${DOMAIN_NAME}
          pages:
            name: gitlab-pages.apps.${SUBDOMAIN}.${DOMAIN_NAME}
        ingress:
          configureCertmanager: true
          class: none
        extraEnv:
          HTTP_PROXY: http://${PROXY_SERVICE}/
          HTTPS_PROXY: http://${PROXY_SERVICE}/
          NO_PROXY: ${SERVICE_CIDR_SUB},localhost,${LAN_CIDR_SUB}.0.0/16,svc,*.svc.cluster.local,svc.cluter.local
        appConfig:
          ldap:
            preventSignin: false
          omniauth:
            enabled: true
            syncProfileAttributes: ["email"]
            allowSingleSignOn: ["openid_connect"]
            blockAutoCreatedUsers: false
            autoSignInWithProvider: "openid_connect"
            autoLinkLdapUser: false
            autoLinkSamlUser: false
            autoLinkUser: ["openid_connect"]
            providers:
              - secret: openid-connect
    version: 6.3.4
